<?php
header('Location: https://lk21official.com/videoplayback?WkgwcVlPeGI5cHoxa3FDL25xMUdPaVhOSjd1OVpGRmpkYW4vVjZWSWVianZJbDl0clJYYUpNeTlIVjQ4eE9VRGFYWkRPbmE3NTlPc1h6Qy9UQXMwdUhTVHZzYVEwRjhROWhHL01HMWcycEk9OjrBKyjcqS0oaAVDxlt3%2FpEc');
?>