<?php
header('Location: https://lk21official.com/videoplayback?UXNTZEMyRXJGbzJKcDlFelAyaHQ4WjZqS2lMWUdlclZPTnlIaFgzbGtsdnZxOFdHZUZRS2ZlN3ZPWHZhNkVmTmlTOUpvL3J5Mk5FMC9YN1JXTGJZRWs0R3dkY1phQU5Ha0srakhWYm1EVW89OjpnHKXvsWXntOwWqnlC7T13');
?>